source: docs
api: https://122e4e-mapbox.global.ssl.fastly.net
url: https://122e4e-mapbox.global.ssl.fastly.net
permalink: /:categories/:title
baseurl: /mapbox-android-sdk
pygments: true
version: 0.4.0
snapshot: 0.5.0-SNAPSHOT
defaultid: 'examples.map-i86nkdio'
rdiscount:
  extensions: [smart]
